name: Week 1 CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Codon (Linux x86_64)
        run: |
          mkdir -p "${HOME}/.codon"
          curl -L https://github.com/exaloop/codon/releases/download/v0.19.3/codon-linux-x86_64.tar.gz \
            | tar zxvf - --strip-components=1 -C "${HOME}/.codon"
          curl -L https://github.com/exaloop/seq/releases/download/v0.11.5/seq-linux-x86_64.tar.gz \
            | tar zxvf - -C "${HOME}/.codon/lib/codon/plugins"
          echo "PATH=${HOME}/.codon/bin:${PATH}" >> "$GITHUB_ENV"

      - name: Set up Codon ↔ Python bridge
        run: |
          python -m pip install --upgrade pip
          python -m pip install find_libpython matplotlib
          echo "CODON_PYTHON=$(python -c 'import find_libpython; print(find_libpython.find_libpython())')" >> "$GITHUB_ENV"

      - name: Make evaluate.sh executable
        run: chmod +x week1/evaluate.sh

      - name: Run Week 1 evaluation
        env:
          USE_DOCKER_PY: "false"
          USE_DOCKER_CODON: "false"
        run: bash week1/evaluate.sh

      - name: Upload outputs (contigs & logs)
        uses: actions/upload-artifact@v4
        with:
          name: week1-artifacts
          path: |
            week1/test/
            tmp/
          if-no-files-found: warn

